// Auto generated by MVCTools - Haqi @ 2026-02-27
// MenuUI 视图层

namespace HachiFramework
{
    public class MenuUIView : UIView
    {
        // 在这里声明 UI 组件引用
        // public Button btn_xxx;
        // public TextMeshProUGUI txt_xxx;

        public override void FindComponents()
        {
            // 在这里查找并缓存 UI 组件
            // btn_xxx = transform.Find("btn_xxx").GetComponent<Button>();
        }

        public override void OnDestroy()
        {
            base.OnDestroy();
        }
    }
}
