// Auto generated by MVCTools - Haqi @ 2026-02-27
// MenuUI 控制层

namespace HachiFramework
{
    public class MenuUICtrl : UICtrl
    {
        private new MenuUIView view => base.view as MenuUIView;
        private new MenuUIModel model => base.model as MenuUIModel;

        public override void OnCreate()
        {
        }

        public override void BindUIEvent()
        {
        }

        public override void OnShow()
        {
        }

        public override void OnHide()
        {
        }

        public override void OnDestroy()
        {
            base.OnDestroy();
        }
    }
}
